version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    user: $UID
    ports:
      - 9200:9200
    environment:
      - ELASTIC_PASSWORD=password
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elk-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    user: $UID
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_PASSWORD=password
    ports:
      - 5601:5601
  apache:
    #image: httpd:2.4.58
    build:
      context: docker/httpd
    command: sh -c "/opt/wait-for-it.sh -t 120 elasticsearch:9200 && httpd-foreground -C \"PidFile /tmp/httpd.pid\""
    #command: sh -c "/opt/wait-for-it.sh -t 120 elasticsearch:9200 && httpd-foreground -C \"PidFile /tmp/httpd.pid\" & /opt/wait-for-it.sh -t 120 elasticsearch:9200 && sleep 5 && /opt/wait-for-it.sh -t 120 elasticsearch:9200 && filebeat setup"
    #command: [httpd-foreground, -C, "PidFile /tmp/httpd.pid", ]
    ports:
      - 8080:80
    depends_on:
      - elasticsearch
    volumes:
      - ./bin/wait-for-it.sh:/opt/wait-for-it.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      - "co.elastic.logs/module=apache2"
      - "co.elastic.logs/module=syslog"
      - "co.elastic.logs/fileset.stdout=access"
      - "co.elastic.logs/fileset.stderr=error"
      - "co.elastic.metrics/module=apache"
      - "co.elastic.metrics/module=syslog"
      - "co.elastic.metrics/metricsets=status"
      #- "co.elastic.metrics/hosts='${data.host}:${data.port}"

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.2
    command: ["--strict.perms=false"]
    user: root
    depends_on:
      - apache
    volumes:
      - ./bin/wait-for-it.sh:/opt/wait-for-it.sh
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:rw
      - filebeat-registry:/usr/share/filebeat/data
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  elk-data:
  filebeat-registry:
